object_detection:
  ros__parameters:
    topic_camera: '/zedx/left/rgb/image_rect_color'
    cam_name: 'camera'
    model_yolo: 'yolov8n.pt'
    model_yolo_custom: '0524_red1.pt'
    topic_object: 'object_detection'
    my_cls: 0
    
real_objection:
  ros__parameters:
    cam_name: 'camera'
    topic_object: 'object_detection'
    topic_camera_depth: '/zedx/left/depth/depth_registered'
    topic_camera_info: '/zedx/left/depth/camera_info'
    base_frame: 'zedx_camera_link'
    topic_person: 'person'
    permit_distance: 5.0
    limit_x: 260.0
    limit_y: 300.0

##################### weight #####################
# 0524_blue1
# 0524_green1
# 0524_red1
# blue
# red
# AI_detect_0520
# Red_colab
