pid_control:
  ros__parameters:
    Kp: 1.2
    Ki: 0.25
    Kd: 0.6
    samplingtime: 0.01
    max_lin_vel: 1.2
    max_ang_vel: 1.5732
    goal_tolerate_dis: 0.25
    goal_tolerate_ang: 0.01

irobot_gazebo_PID:
  ros__parameters:
    T: 5.0
    samplingtime: 0.1
    max_acc: 3.0
    max_ang_acc: 3.0
    lim_max_vel: 0.8
    lim_min_vel: 0.0
    lim_max_ang_vel: 1.5732
    goal_tolerate_dis: 0.25
    goal_tolerate_ang: 0.01
    kp_dis : 1.0
    kp_ang : 1.5
    ki_ang : 0.015
    kd_ang : 0.05
