point_cal:
  ros__parameters:
    topic_object: 'thanh'
    row_distance: 2.5
    parm_LSM: 2
    y_Translation: 2.5
    x_nearset_min: 1.75
    x_nearset_max: 5.5
    y_nearset_max: 5.5
    x_distinguish_LR: 1.0
    topic_tree_left: 'left_tree_array'
    topic_tree_rigt: 'right_tree_array'
    base_link_frame: 'base_link'
    camera_left_frame: 'camera_left_link'
    camera_right_frame: 'camera_right_link'
    
